### PR TITLE
fix(keymaps): extracted keymaps from data file for more modularity

### PR DESCRIPTION
**Pull request by nkxxll**
## Changes rel. to issue #14 

- added dev_config.json file
- removed keymaps from data.json
- added the option to use a config.json in .config/openup/config.json

## TODO

- [x] use default keymaps when ~/.config/openup/config.json does not exist (not tested tho)
- [ ] add an option to generate a config.json in install script

### CODE REVIEW

**Comment by Horryportier** [comment]
I've updated the un/install scripts but i can't push it into this pr if can allow me somehow to do that it would be great.

**Comment by nkxxll** [comment]
> I've updated the un/install scripts but i can't push it into this pr if can allow me somehow to do that it would be great.

I have "Allow edits by maintainers" turned on I don't know why it doesn't work...

Can I find your code somewhere? Then I could merge it myself.

**Comment by Horryportier** [comment]
Then i don't know meaybe i did something wrong. But i need to give username and password to push but it says that capability is no longer supported and using token dose not work ether. So i think i just marge this branch and rewrite my changes in new one its not gonna take long.

**Review by Horryportier — APPROVED** [review]
all good

**Pull request merged**
